### ISSUE TITLE
Build a rosbag_validate

### ISSUE THREAD

**Issue by SirVer** [cartographer-project/cartographer_ros#529]
Many of the tuning issues we receive in Cartographer are easy to explain by looking through the bags provided. Below I list some issues that could have benefited from a binary that runs through bags and does automatic checks for validity and likeliness of data as wells as obvious configuration errors.

Some examples for inspiration what to check for with example issues where this showed:

- [x] timing (#511, #317, googlecartographer/cartographer#377, googlecartographer/cartographer#193), most of these can be tracked with a histogram + min/max of delta timestamps for each sensor.
- [x] significant difference in a) `rosbag::MessageInstance::getTime` and b) `msg->header.stamp`. The problem is that Cartographer will generate pose timestamps from b) since it is purely data driven, but rViz will want to visualize poses for `ros::Time::Now()` which is published by rosbag and `cartographer_offline_node` using a). (#488, https://github.com/googlecartographer/cartographer/issues/447)
- [x] incomplete IMU data (#424). Especially wrong units (G instead of m/s^2 or gravity being removed)
- [x] fastest sensor is still very slow (#372)
- [x] frames fighting: TF published from Cartographer are also in the bag (#356).
- [x] scans are never changing shape (#356)
- [ ] ROS data type validation: For example invalid laser messages (#354, #270 ), invalid IMU messages (#273, #268, #462), [odometry data with invalid quaternions](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/google-cartographer/Jtml5Kf9Cg4/hM63bqFfBgAJ).
 - [ ] header time stamps not strictly increasing (https://github.com/googlecartographer/cartographer_ros/issues/699)

**Comment by ojura** [comment]
IIRC, Cartographer has a zero velocity assumption at the beginning of the bag, so checking for that might also be useful.

**Comment by MichaelGrupp** [comment]
Should be done now in `cartographer_rosbag_validate`.
